# Site settings
title: Douglas
description: Chainable AI App Runner & Builder. Don't Panic - Your digital towel is ready.

# Jekyll theme - perfect for your retro terminal aesthetic
theme: jekyll-theme-hacker

# GitHub Pages configuration
url: "https://oldmill1.github.io"
baseurl: "/douglas"

# Markdown processor
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap