# Site settings
title: Douglas
description: An AI-First App Runner & Builder. Don't Panic - Your digital towel is ready. Build chainable AI workflows called "Galaxies" with OpenAI integration.
theme: jekyll-theme-hacker

# GitHub Pages configuration
url: "https://oldmill1.github.io"
baseurl: "/douglas"

# Markdown processor
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jektml-sitemap

# Additional settings
author: Ankur Taxali
github_username: @oldmill1

# Collections (for potential galaxy showcase)
collections:
  galaxies:
    output: true
    permalink: /:collection/:name/

# Navigation (if you want a menu)
navigation:
  - title: Home
    url: /
  - title: Galaxies
    url: /galaxies/
  - title: Documentation
    url: /docs/
  - title: GitHub
    url: https://github.com/oldmill1/douglas